In [1]:
import pandas as pd
import numpy as np
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler

In [2]:
df = pd.read_csv("https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv")

In [3]:
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [4]:
df.shape

(569, 33)

In [19]:
df.drop(columns=['id','Unnamed: 32'],inplace=True)

In [20]:
df.head()

  diagnosis  radius_mean  ...  symmetry_worst  fractal_dimension_worst
0         M        17.99  ...          0.4601                  0.11890
1         M        20.57  ...          0.2750                  0.08902
2         M        19.69  ...          0.3613                  0.08758
3         M        11.42  ...          0.6638                  0.17300
4         M        20.29  ...          0.2364                  0.07678

[5 rows x 31 columns]

In [21]:
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2)

In [22]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [23]:
X_train

array([[-0.17070395,  2.14012386, -0.23180235, ..., -0.8407805 ,
        -0.32570062, -0.7441363 ],
       [-0.31974856, -0.73834354, -0.34407993, ..., -0.44698663,
         0.69997372, -0.3029421 ],
       [-0.21656383,  0.55266343, -0.2587324 , ..., -0.86600626,
        -0.42265492, -0.97415088],
       ...,
       [-0.76974863, -0.08805855, -0.80023346, ..., -0.77703634,
         0.64894515, -0.78237694],
       [-1.15382512,  0.48333157, -1.17228239, ..., -1.3244506 ,
        -0.91252923, -0.17338055],
       [ 1.10477395,  0.42117198,  1.36369924, ...,  1.25265611,
         0.61152419,  2.06341127]], shape=(455, 30))

In [24]:
y_train

377    B
403    B
361    B
84     B
117    M
      ..
15     M
359    B
289    B
425    B
400    M
Name: diagnosis, Length: 455, dtype: object

In [ ]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [26]:
y_train

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1])

#### NumPy arrays to PyTorch tensors

In [29]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [30]:
X_train_tensor.shape

torch.Size([455, 30])

In [32]:
y_train_tensor.shape

torch.Size([455])

In [52]:
class SimpleNN():
    def __init__(self,X):

        self.weights = torch.rand(X.shape[1],1,dtype=torch.float64,requires_grad=True)
        self.bias = torch.zeros(1,dtype=torch.float64,requires_grad=True)
    
    def forward(self,X):
        z = torch.matmul(X,self.weights) + self.bias
        y_pred = torch.sigmoid(z)
        return y_pred
    
    def loss_fun(self,y_pred,y):
        epsilon = 1e-7
        y_pred = torch.clamp(y_pred,epsilon,1-epsilon)

        loss = -(y_train_tensor*torch.log(y_pred) + (1-y_train_tensor)*torch.log(1-y_pred)).mean()
        return loss

In [58]:
learning_rate = 0.1
epochs = 25

Training pipeline

In [59]:
model = SimpleNN(X_test_tensor)

#loop
for epoch in range(epochs):
        
    #forward prop
    y_pred = model.forward(X_train_tensor)
    
    #loss calculate
    loss = model.loss_fun(y_pred,y_train_tensor)

    #backward prop
    loss.backward()

    #params update
    with torch.no_grad():
        model.weights -= learning_rate*model.weights.grad
        model.bias -= learning_rate*model.bias.grad

    #zero gradients
    model.weights.grad.zero_()
    model.bias.grad.zero_()

    #print loss in each epoch
    print(f"Epoch: {epoch+1}, Loss: {loss.item()}")

Epoch: 1, Loss: 3.371596717926537
Epoch: 2, Loss: 3.235681583463339
Epoch: 3, Loss: 3.0971235206527052
Epoch: 4, Loss: 2.9538933465495028
Epoch: 5, Loss: 2.805039888432478
Epoch: 6, Loss: 2.652162639187678
Epoch: 7, Loss: 2.4924750545841357
Epoch: 8, Loss: 2.323843878597008
Epoch: 9, Loss: 2.1557938680700195
Epoch: 10, Loss: 1.990076095039535
Epoch: 11, Loss: 1.8274300131144958
Epoch: 12, Loss: 1.670266927698451
Epoch: 13, Loss: 1.513641177397022
Epoch: 14, Loss: 1.3673995506630126
Epoch: 15, Loss: 1.2376466243038569
Epoch: 16, Loss: 1.1263408641551071
Epoch: 17, Loss: 1.0345609817335761
Epoch: 18, Loss: 0.9620110581900083
Epoch: 19, Loss: 0.9068845104450801
Epoch: 20, Loss: 0.8662437237375529
Epoch: 21, Loss: 0.8367288784866252
Epoch: 22, Loss: 0.8152050168718646
Epoch: 23, Loss: 0.7991232005558745
Epoch: 24, Loss: 0.7866170504331795
Epoch: 25, Loss: 0.7764356576682951

In [60]:
model.bias

tensor([-0.1585], dtype=torch.float64, requires_grad=True)

In [61]:
model.weights

tensor([[-0.0128],
        [ 0.3910],
        [ 0.3974],
        [ 0.2151],
        [-0.1675],
        [-0.3064],
        [-0.4699],
        [ 0.2208],
        [-0.2658],
        [ 0.7550],
        [-0.1907],
        [ 0.2063],
        [-0.0647],
        [-0.1014],
        [-0.1440],
        [ 0.0448],
        [ 0.2983],
        [ 0.2189],
        [ 0.5325],
        [ 0.1189],
        [ 0.2503],
        [-0.0979],
        [-0.0283],
        [ 0.3035],
        [ 0.3399],
        [-0.1469],
        [-0.1285],
        [-0.3339],
        [-0.1191],
        [-0.3023]], dtype=torch.float64, requires_grad=True)

#### Evaluation

In [68]:
with torch.no_grad():
    y_pred = model.forward(X_test_tensor)
    y_pred = (y_pred > 0.5).float()
    accuracy = (y_pred == y_test_tensor).float().mean()
    print(f"Accuracy: {accuracy.item()}")

Accuracy: 0.5123114585876465